#
###################################
# Site wide configuration
####################################
#
title: ThanhDatIO
email: datchuthanh@gmail.com
description: ThanhDatIO Blog
url: https://blog.thanhdat.io # the base hostname & protocol for your site
keywords: ["ThanhDatIO", "Chu Thành Đạt", "Người cầm trứng","blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Ho_Chi_Minh
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-gist
  - jemoji

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: ThanhDatIO
  avatar: avatar.jpg
  job: "Người cầm trứng"
  bio: "Mình là Chu Thành Đạt, hiện tại mình đang làm việc liên quan đến lĩnh vực Công nghệ thông tin."
  email: datchuthanh@gmail.com
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: thanhdatio #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
